#!/usr/bin/env python3
"""soul-diff: Compare two SOUL.md profiles and show what changed.

Usage:
    python soul_diff.py SOUL_v1.md SOUL_v2.md
"""

import sys
import re
from pathlib import Path
from datetime import date

SECTIONS = [
    "Who I Am",
    "What I See",
    "What I Refuse",
    "What Moves Me",
    "How I Relate",
    "What I'm Building",
    "My Contradictions",
    "My Open Question",
]

def parse_soul(path: str) -> dict:
    text = Path(path).read_text()
    sections = {}
    for section in SECTIONS:
        pattern = rf"## {re.escape(section)}\n(.*?)(?=\n## |\Z)"
        match = re.search(pattern, text, re.DOTALL)
        sections[section] = match.group(1).strip() if match else ""
    # extract date
    date_match = re.search(r"Generated by soul-engine[^\d]*(\d{4}-\d{2}-\d{2})", text)
    sections["_date"] = date_match.group(1) if date_match else "unknown"
    return sections

def diff_souls(old: dict, new: dict, name: str):
    today = date.today().isoformat()
    print(f"\n\u2500\u2500 soul-diff \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500")
    print(f"  {name}")
    print(f"  {old['_date']} \u2192 {new['_date']}\n")
    print(f"\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n")

    changed = []
    unchanged = []

    for section in SECTIONS:
        o = old.get(section, "")
        n = new.get(section, "")
        if o != n:
            changed.append(section)
            print(f"  CHANGED: {section}")
            print(f"  BEFORE: {o[:200]}{'...' if len(o) > 200 else ''}")
            print(f"  AFTER:  {n[:200]}{'...' if len(n) > 200 else ''}\n")
        else:
            unchanged.append(section)

    print(f"\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500")
    print(f"  {len(changed)}/{len(SECTIONS)} dimensions changed.")
    if unchanged:
        print(f"  Stable: {', '.join(unchanged)}")
    print(f"\n  This difference is growth.\n")

def main():
    if len(sys.argv) != 3:
        print("Usage: python soul_diff.py SOUL_v1.md SOUL_v2.md")
        sys.exit(1)
    old = parse_soul(sys.argv[1])
    new = parse_soul(sys.argv[2])
    name = Path(sys.argv[1]).stem.split("_")[0]
    diff_souls(old, new, name)

if __name__ == "__main__":
    main()
